export {
  legalCaseDefaults,
  legalCaseFormSchema,
  legalCaseLabel,
  createResearchCheckKey,
  isHttpUrl,
  legalCaseClassifications,
  legalResearchCategories,
  legalTargetRoles,
  courtLevels,
  verdictStatuses,
  type LegalCase,
  type LegalCaseInput,
  type LegalResearchCategory,
} from './model/legal-case.schema'
