/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppAssignmentsRouteImport } from './routes/_app.assignments'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppAssignmentsIndexRouteImport } from './routes/_app.assignments.index'
import { Route as AppAssignmentsAssignmentIdRouteImport } from './routes/_app.assignments.$assignmentId'
import { Route as AppAssignmentsNewRouteImport } from './routes/_app.assignments.new'
import { Route as AppReportsSubmittedRouteImport } from './routes/_app.reports.submitted'
import { Route as AppAssignmentsAssignmentIdIndexRouteImport } from './routes/_app.assignments.$assignmentId.index'
import { Route as AppAssignmentsAssignmentIdReportRouteImport } from './routes/_app.assignments.$assignmentId.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsIndexRoute = AppAssignmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAssignmentsRoute,
} as any)
const AppAssignmentsAssignmentIdRoute =
  AppAssignmentsAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => AppAssignmentsRoute,
  } as any)
const AppAssignmentsNewRoute = AppAssignmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAssignmentsRoute,
} as any)
const AppReportsSubmittedRoute = AppReportsSubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppAssignmentsAssignmentIdIndexRoute =
  AppAssignmentsAssignmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAssignmentsAssignmentIdRoute,
  } as any)
const AppAssignmentsAssignmentIdReportRoute =
  AppAssignmentsAssignmentIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AppAssignmentsAssignmentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/assignments': typeof AppAssignmentsRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/assignments/$assignmentId': typeof AppAssignmentsAssignmentIdRouteWithChildren
  '/assignments/new': typeof AppAssignmentsNewRoute
  '/reports/submitted': typeof AppReportsSubmittedRoute
  '/assignments/': typeof AppAssignmentsIndexRoute
  '/assignments/$assignmentId/report': typeof AppAssignmentsAssignmentIdReportRoute
  '/assignments/$assignmentId/': typeof AppAssignmentsAssignmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/assignments/new': typeof AppAssignmentsNewRoute
  '/reports/submitted': typeof AppReportsSubmittedRoute
  '/assignments': typeof AppAssignmentsIndexRoute
  '/assignments/$assignmentId/report': typeof AppAssignmentsAssignmentIdReportRoute
  '/assignments/$assignmentId': typeof AppAssignmentsAssignmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/assignments': typeof AppAssignmentsRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/assignments/$assignmentId': typeof AppAssignmentsAssignmentIdRouteWithChildren
  '/_app/assignments/new': typeof AppAssignmentsNewRoute
  '/_app/reports/submitted': typeof AppReportsSubmittedRoute
  '/_app/assignments/': typeof AppAssignmentsIndexRoute
  '/_app/assignments/$assignmentId/report': typeof AppAssignmentsAssignmentIdReportRoute
  '/_app/assignments/$assignmentId/': typeof AppAssignmentsAssignmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/assignments'
    | '/profile'
    | '/reports'
    | '/assignments/$assignmentId'
    | '/assignments/new'
    | '/reports/submitted'
    | '/assignments/'
    | '/assignments/$assignmentId/report'
    | '/assignments/$assignmentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/profile'
    | '/reports'
    | '/assignments/new'
    | '/reports/submitted'
    | '/assignments'
    | '/assignments/$assignmentId/report'
    | '/assignments/$assignmentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_app/assignments'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/assignments/$assignmentId'
    | '/_app/assignments/new'
    | '/_app/reports/submitted'
    | '/_app/assignments/'
    | '/_app/assignments/$assignmentId/report'
    | '/_app/assignments/$assignmentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/assignments': {
      id: '/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignments/': {
      id: '/_app/assignments/'
      path: '/'
      fullPath: '/assignments/'
      preLoaderRoute: typeof AppAssignmentsIndexRouteImport
      parentRoute: typeof AppAssignmentsRoute
    }
    '/_app/assignments/$assignmentId': {
      id: '/_app/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AppAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AppAssignmentsRoute
    }
    '/_app/assignments/new': {
      id: '/_app/assignments/new'
      path: '/new'
      fullPath: '/assignments/new'
      preLoaderRoute: typeof AppAssignmentsNewRouteImport
      parentRoute: typeof AppAssignmentsRoute
    }
    '/_app/reports/submitted': {
      id: '/_app/reports/submitted'
      path: '/submitted'
      fullPath: '/reports/submitted'
      preLoaderRoute: typeof AppReportsSubmittedRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/assignments/$assignmentId/': {
      id: '/_app/assignments/$assignmentId/'
      path: '/'
      fullPath: '/assignments/$assignmentId/'
      preLoaderRoute: typeof AppAssignmentsAssignmentIdIndexRouteImport
      parentRoute: typeof AppAssignmentsAssignmentIdRoute
    }
    '/_app/assignments/$assignmentId/report': {
      id: '/_app/assignments/$assignmentId/report'
      path: '/report'
      fullPath: '/assignments/$assignmentId/report'
      preLoaderRoute: typeof AppAssignmentsAssignmentIdReportRouteImport
      parentRoute: typeof AppAssignmentsAssignmentIdRoute
    }
  }
}

interface AppAssignmentsAssignmentIdRouteChildren {
  AppAssignmentsAssignmentIdReportRoute: typeof AppAssignmentsAssignmentIdReportRoute
  AppAssignmentsAssignmentIdIndexRoute: typeof AppAssignmentsAssignmentIdIndexRoute
}

const AppAssignmentsAssignmentIdRouteChildren: AppAssignmentsAssignmentIdRouteChildren =
  {
    AppAssignmentsAssignmentIdReportRoute:
      AppAssignmentsAssignmentIdReportRoute,
    AppAssignmentsAssignmentIdIndexRoute: AppAssignmentsAssignmentIdIndexRoute,
  }

const AppAssignmentsAssignmentIdRouteWithChildren =
  AppAssignmentsAssignmentIdRoute._addFileChildren(
    AppAssignmentsAssignmentIdRouteChildren,
  )

interface AppAssignmentsRouteChildren {
  AppAssignmentsAssignmentIdRoute: typeof AppAssignmentsAssignmentIdRouteWithChildren
  AppAssignmentsNewRoute: typeof AppAssignmentsNewRoute
  AppAssignmentsIndexRoute: typeof AppAssignmentsIndexRoute
}

const AppAssignmentsRouteChildren: AppAssignmentsRouteChildren = {
  AppAssignmentsAssignmentIdRoute: AppAssignmentsAssignmentIdRouteWithChildren,
  AppAssignmentsNewRoute: AppAssignmentsNewRoute,
  AppAssignmentsIndexRoute: AppAssignmentsIndexRoute,
}

const AppAssignmentsRouteWithChildren = AppAssignmentsRoute._addFileChildren(
  AppAssignmentsRouteChildren,
)

interface AppReportsRouteChildren {
  AppReportsSubmittedRoute: typeof AppReportsSubmittedRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsSubmittedRoute: AppReportsSubmittedRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAssignmentsRoute: typeof AppAssignmentsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAssignmentsRoute: AppAssignmentsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
